services:

  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "3.0"
          memory: 4G
        reservations:
          cpus: "1.0"
          memory: 1G
